import 'package:shelter_adventure/components/encounter/encounter.dart';

final List<Encounter> encounters = [
  Encounter(
    text:
        'A customer brings in their sick gecko. He hasn\'t eaten a cricket in a week. He looks unhappy.',
    agreeText: 'Accept the gecko as a patient',
    disagreeText: 'Refer the gecko to counseling',
    agreeResultText:
        'you set up a small habitat on your desk and send your assistant to find crickets',
    disagreeResultText:
        'the gecko resumes eating, but does not forgive his parents',
    agreeEffect: [-10, -10, 20, 10],
    disagreeEffect: [10, 10, -10, 0],
  ),
  Encounter(
    text:
        'Two neighborhood cats ambush you in the alley behind the shelter and demand pets, or else',
    agreeText: 'Pet them until they are satisfied',
    disagreeText: 'Catch them and bring them inside to check for microchips',
    agreeResultText: 'They let you leave after a few minutes',
    disagreeResultText: 'You have two more stray cats to feed',
    agreeEffect: [-7, 0, 4, 7],
    disagreeEffect: [-5, 10, -5, 0],
  ),
  Encounter(
    text: 'There are ants in the break room',
    agreeText: 'Get the vacuum',
    disagreeText: 'Let them be - you have work to do',
    agreeResultText: 'Vrooooom!',
    disagreeResultText: 'The little one stops to tie its shoe',
    agreeEffect: [4, 0, 0, 0],
    disagreeEffect: [12, 0, 0, -8],
  ),
  Encounter(
      text:
          'A local reporter wants to interview you about a rise in stray cats in the area.',
      agreeText: 'Give the interview',
      disagreeText: 'You don\'t have time for that!',
      agreeEffect: [-5, 12, 6, -5],
      disagreeEffect: [5, 0, -5, 3],
      agreeResultText: 'It goes well.',
      disagreeResultText: 'He sends you a snarky email two weeks later'),
  Encounter(
      text:
          'Four friends approach you and gently remind you about that time you promised to throw a party for all of the neighborhood dogs',
      agreeText: 'Start planning',
      disagreeText: 'Deny that ever happened',
      agreeResultText: 'It takes longer to put together than you anticipated, and one of the dogs throws up on the cake',
      disagreeResultText: 'You feel slightly ashamed but justified in your decision',
      agreeEffect: [-6, 8, 8, -4],
      disagreeEffect: [5, 0, -10, 10]),
  Encounter(
      text:
          'You have a grant application to finish by tomorrow, but you have tickets to go see a big rock band. The concert starts in an hour.',
      agreeText: 'Leave the paperwork for tomorrow',
      disagreeText: 'Stay and finish the paperwork',
      agreeResultText: 'Tomorrow is really busy and it doesn\'t get done',
      disagreeResultText: 'Your friends have a great time at the concert',
      agreeEffect: [-13, 0, 0, 20],
      disagreeEffect: [12, 12, 0, -16]),
  Encounter(
    text:
        'Your phone rings. It is the mayor. He wants you to adopt a crocodile he says was found in a pool.',
    agreeText: 'Get the bathtub ready',
    disagreeText:
        'Tell the mayor politely that is ridiculous and that he\'ll have to come up with a better plan',
    agreeResultText:
        'The food bill goes up significantly, and the mayor boasts of brokering the deal at a campaign speech.',
    disagreeResultText: 'The crocodile is sent to florida at taxpayer expense',
    agreeEffect: [-25, 15, 25, -12],
    disagreeEffect: [6, -5, -10, 12],
  ),
  Encounter(
      text: 'The neighbors ask if you can look after their rabbits',
      agreeText: 'Tell them no problem',
      disagreeText: 'Freeze in place and don\'t respond to their questions',
      agreeResultText: 'The rabbits are irritable',
      disagreeResultText: 'They give you a strange look as they leave',
      agreeEffect: [-6, 8, 11, -2],
      disagreeEffect: [7, -1, -12, 10]),
  Encounter(
    text:
        'A dirty, disoriented person walks into the shelter, and asks for help finding their way home.',
    agreeText: 'Try to figure out where they live',
    disagreeText: 'Give them bus fare',
    agreeResultText:
        'You spend several minutes teasing apart what they actually know about their life, until they finally explain they are a millionaire testing your compassion. Big donation incoming!',
    disagreeResultText: 'They mumble their thanks and wander out the door.',
    agreeEffect: [29, -3, -1, -5],
    disagreeEffect: [3, 2, -5, 1],
  ),
  Encounter(
    text: 'A dog was stolen!',
    agreeText: 'Check the security cameras and call the cops!',
    disagreeText: 'That\'s as good as adopting, right?',
    agreeResultText:
        'You recognize a former employee and quickly recover rover.',
    disagreeResultText: 'The kennels are a little bit quieter.',
    agreeEffect: [16, 0, -2, 0],
    disagreeEffect: [-4, 0, 4, 5],
  ),
  Encounter(
    text:
        'The fire chief calls and asks if you might have any Dalmatians they can rent for a fundraiser event. ',
    agreeText:
        'Get the sharpie and all your white short-haired dogs ready for showtime',
    disagreeText: 'Offer him all your mutts for free instead',
    agreeResultText: 'The fundraiser is a big success. Everyone was fooled. ',
    disagreeResultText:
        'Two dogs find forever homes. The dogs stole the show and the fire department didn\'t raise any money.',
    agreeEffect: [2, 4, 4, -2],
    disagreeEffect: [0, 13, -5, 0],
  ),
  Encounter(
    text: 'The sausages you were about to eat are missing from your desk.',
    agreeText: 'Order a sandwich from the deli instead',
    disagreeText: 'Line the dogs up and see who looks the most guilty',
    agreeResultText:
        'You ask for no pickle, but you get pickle. You suspect it was intentional. ',
    disagreeResultText: 'You are unable to locate the sausage thief.',
    agreeEffect: [3, 5, 0, -2],
    disagreeEffect: [-4, 1, 0, 3],
  ),
  Encounter(
    text:
        'Your biscuit supplier has decided to quit the industry and go to college to pursue a career in international relations.',
    agreeText: 'Wish her luck in all future endevors',
    disagreeText: 'Try to talk her out of it',
    agreeResultText: 'Ten years later she becomes the ambassador to Finland. ',
    disagreeResultText: 'She is not convinced, but seems shaken by your words',
    agreeEffect: [0, -1, 7, 0],
    disagreeEffect: [0, 0, 0, 0],
  ),
  Encounter(
    text:
        'Wiley the weasel, a local radio personality and real-life weasel, is brought in by DJ Mike. In a hushed tone, he explains, well ... Wiley\'s poop has been smelling kind of funny recently',
    agreeText: 'Get Wiley on a diet of carrots and cabbage',
    disagreeText: 'Tell Mike you have real problems to solve',
    agreeResultText:
        'Wiley is back on air the next morning, squeaky as ever and apparently irritated by local drivers',
    disagreeResultText:
        'You work efficiently for the rest of the afternoon. On the radio the next morning, Wiley sounds bloated and un-energetic. ',
    agreeEffect: [-3, 3, 6, 0],
    disagreeEffect: [9, -2, -5, 3],
  ),
  Encounter(text: 'A crotchety dog comes into the shelter with a scrawled note tucked in his collar: "kurst prints - pleez kiss"',
    agreeText: 'Smooch that pooch!',
    disagreeText: 'Maybe just a little hug instead',
    agreeResultText: 'The dog\'s arthritis clears up in the blink of an eye. He thanks you with the keys to his father\'s castle... actually just spits out a milk bone for you.',
    disagreeResultText: 'The dog\'s eyes bulge, and he tries to squirm away.',
    agreeEffect: [0, 1, -4, 0],
    disagreeEffect: [0, -5, 0, 3],
  ),
  Encounter(text: 'STICK \'EM UP!',
    agreeText: 'Empty the register',
    disagreeText: 'Run out the back',
    agreeResultText: 'You dole out the cash and the robber swiftly departs.',
    disagreeResultText: 'The cash is relatively safe, but the steals all the decorations from your front office!',
    agreeEffect: [-5, 0, 0, -2],
    disagreeEffect: [0, 0, -1, -8],
  ),
  Encounter(text: 'There is broken glass and the front door is wide open this morning.',
    agreeText: 'Clean up from the robbery and get on with things.',
    disagreeText: 'Clean up, and try to solve the crime yourself!',
    agreeResultText: 'The morning is shot, but you get most of your work done for the day.',
    disagreeResultText: 'You clip on your sleuthing bonnet and spend the day follow the trail of kibble to the house of a former adopter! The news story goes viral!',
    agreeEffect: [-3, 0, 4, -5],
    disagreeEffect: [-7, 0, 16, -1],
  ),
  Encounter(text: 'A high-volume shelter can transfer 50 dogs to you, but it has to be all or none.',
    agreeText: 'The more, the hairier!',
    disagreeText: 'No room at the Rin Tint Inn',
    agreeResultText: 'It seems like every time you clean something up, there\'s suddenly two more to take its place.',
    disagreeResultText: 'It\'s actually kind of quite in here today.',
    agreeEffect: [-10, 15, 4, -4],
    disagreeEffect: [5, -1, 0, 3],
  ),
  Encounter(text: 'An employee has been chronically late to work',
    agreeText: 'Ask them to come in much, much later.',
    disagreeText: 'Explain why it\'s important to be on time',
    agreeResultText: 'They are confused by your phrasing, and it takes several minutes of explanation before they understand that you are firing them.',
    disagreeResultText: 'They clean up their act over the next few weeks. ',
    agreeEffect: [1, 4, 0, -8],
    disagreeEffect: [1, 0, 0, 0],
  ),
  Encounter(text: 'Oh no! The computers are down, and you can\'t process adoptions or look up which dogs need medication!',
    agreeText: 'Use paper and copy everything back into the computer later',
    disagreeText: 'Hold off on adoptions for now',
    agreeResultText: 'You get more animals into their forever homes, but it a lot more work too.',
    agreeEffect: [-18, 3, 1, 0],
    disagreeEffect: [4, -3, -4, 1],
  ),
  Encounter(text: 'The power is out!',
    agreeText: 'Buy a generator',
    disagreeText: 'Evacuate',
    agreeResultText: 'That was a shockingly good idea.',
    disagreeResultText: 'You set up shop in an abandoned warehouse across town.',
    agreeEffect: [-1, 10, 0, 0],
    disagreeEffect: [0, 10, 0, -3],
  ),
  Encounter(text: 'No customers come in today. How do you spend the extra time?',
    agreeText: 'Cleaning',
    disagreeText: 'Writing grants',
    agreeResultText: 'Spot never looked so spotless!',
    disagreeResultText: 'You get all the dough you knead.',
    agreeEffect: [0, 17, 0, 5],
    disagreeEffect: [6, 0, 1, 0],
  ),
  Encounter(text: 'You find a field of catnip in the forest. Do you keep it for the shelter cats or sell it, to buy less-recreational supplies.',
    agreeText: 'Every cat deservse a little break',
    disagreeText: 'Let\'s get kibble before we go crazy',
    agreeResultText: 'The resulting videos are what the internet is all about. It\'s social media gold!',
    disagreeResultText: 'With a level head and an even keel, you steer the ship toward gradual prosperity.',
    agreeEffect: [-3, 0, 26, 0],
    disagreeEffect: [13, 3, 0, 0],
  ),
  Encounter(text: 'Time for fundraising!',
    agreeText: 'Bake sale',
    disagreeText: 'Raffle',
    agreeResultText: 'The muffins sell like hot cakes!',
    disagreeResultText: 'You make a lot of business connections while soliciting donations.',
    agreeEffect: [5, 1, 0, 0],
    disagreeEffect: [0, 0, 6, 0],
  ),
  Encounter(text: 'You plan to attend an enrichment seminar. How many other staff members do you bring?',
    agreeText: 'Just me!',
    disagreeText: 'Whoever wants to come!',
    agreeResultText: 'You learn plenty, and enjoy a working vacation.',
    disagreeResultText: 'You all split up, so you can attend more talks. ',
    agreeEffect: [4, 0, 0, 9],
    disagreeEffect: [25, 0, 0, -4],
  ),
  Encounter(text: 'An employee has been stealing meds',
    agreeText: 'Fire them',
    disagreeText: 'Fire them and involve the police',
    agreeResultText: 'They\'re out of your hair, at least.',
    disagreeResultText: 'Some tough love was necessary, and it turns out they had been stealing from all sorts of places around town. You stopped a crime wave!',
    agreeEffect: [2, 5, 0, -2],
    disagreeEffect: [-2, 3, 16, -1],
  ),
  Encounter(text: 'The Duranda dog bed company just donated 1,001 extra-large dog beds. What a windfall!',
    agreeText: 'Free bed with every adoption',
    disagreeText: 'Sell them',
    agreeResultText: 'You pay it forward. Everyone\'s a winner in this snooze fest!',
    disagreeResultText: 'You roll out of bed each day and wonder if you\'ll ever be able to roll out all those beds. Eventually, you do. Ka-ching!',
    agreeEffect: [0, 6, 18, 0],
    disagreeEffect: [28, 0, 0, 0],
  ),
  Encounter(text: 'You\'re running low on kibble.',
    agreeText: 'Purchase kibble',
    disagreeText: 'Solicit donations from the public',
    agreeResultText: 'You swap that cheddar for chow... der. Wait, that\'s not right. You trade that bread for biscuits... not quite. You spend that dough on doggy din din... close enough.',
    disagreeResultText: 'You spend time drawing on your greatest resource, the community. And they come through with all the cans and bags you need for quite a while. ',
    agreeEffect: [-5, 4, 0, 0],
    disagreeEffect: [5, 0, -2, -1],
  ),
  Encounter(text: 'There are very few animals in the shelter right now.',
    agreeText: 'Arrange for a van load from other crowded shelters',
    disagreeText: 'Take a few extra days for some top-to-bottom cleaning',
    agreeResultText: 'Your contacts are relieved to get your help. And the new puppies and kitties are so dang CUTE!',
    disagreeResultText: 'It really gets everywhere, doesn\'t it?',
    agreeEffect: [-12, 7, 4, 0],
    disagreeEffect: [19, -16, 0, 5],
  ),
  Encounter(text: 'It’s kitten season! So it\'s a lot like that episode of Star Trek with tribbles.',
    agreeText: 'Get them spayed and neutered ASAP',
    disagreeText: 'Wait for cheaper appointments',
    agreeResultText: 'It costs plenty more, but you can also adopt them out sooner.',
    disagreeResultText: 'Their tenure drums up a lot of interest. Every one of them finds a purrfect-fit forever home!',
    agreeEffect: [2, 5, 0, 0],
    disagreeEffect: [-4, 16, 4, 0],
  ),
  Encounter(text: 'The motion detectors go off at night. You discover a member of the public was hiding in the shleter after hours!',
    agreeText: 'Ask why',
    disagreeText: 'Wait and watch on the security cameras',
    agreeResultText: '"If you must be nosy. The kennel looked cozy. And then I got doze-y! Does that answer your posey?"',
    disagreeResultText: 'They bump their way to the front office, directly to the donation box... into which they stuff a fat roll of bennies!',
    agreeEffect: [0, 0, 0, 20],
    disagreeEffect: [26, 0, 0, 0],
  ),
  Encounter(text: 'The most playful little tortoise shell kitty was rescued from a garbage bin. What name do you choose?',
    agreeText: 'Oscar',
    disagreeText: 'Diver',
    agreeResultText: 'This kitty is no grouch, but that\'s certainly a tale worth telling.',
    disagreeResultText: 'Diver goes on to have a fulfilling career in coral reef conservation.',
    agreeEffect: [0, 4, 0, 1],
    disagreeEffect: [0, 4, 0, 4],
  ),
  Encounter(text: 'You see an alum on the street. Do you say hello?',
    agreeText: 'Howdy paw-rdner!',
    disagreeText: 'Maybe just a nod in passing.',
    agreeResultText: 'You are mistaken, and the owner is a real jerk about it! They seem to think it\'s insulting that their "purebred" looks anything like a shelter dog.',
    disagreeResultText: 'You make eye-contact, and Sbarky remembers you! She pulls at the leash to get some pets. You learn that her new name is Elephant, or Ellie for short.',
    agreeEffect: [0, 0, -3, -3],
    disagreeEffect: [0, 0, 3, 1],
  ),
  Encounter(text: 'Someone wants to buy a puppy as a Christmas present for their kid',
    agreeText: 'Srsly...? no.',
    disagreeText: 'Ok, but you know you\'ll be doing all the work',
    agreeResultText: 'You wisely decline to adopt to someone with unrealistic expectations.',
    disagreeResultText: 'They bring the puppy back in February when it starts teething. Jerk.',
    agreeEffect: [0, 4, 0, 3],
    disagreeEffect: [0, -3, 0, 0],
  ),
  Encounter(text: 'After a few weeks, it seems that one of the puppies is actually a dire wolf.',
    agreeText: 'Try to adopt it out real quick',
    disagreeText: 'Undertake an arduous trek to the frozen north and return it to its natural habitat',
    agreeResultText: 'Watching the channel 6 news a few months later, you are not proud of mayhem you caused.',
    disagreeResultText: 'You find your old snow shoes and head out. Several weeks later, you return (buffer than ever) and hope that little Thor-Garden is hunting well on the ice shelf.',
    agreeEffect: [5, 3, -4, -9],
    disagreeEffect: [-7, 0, 4, 1],
  ),
  Encounter(text: 'A former felon wants to adopt',
    agreeText: 'Yes... and?',
    disagreeText: 'Maybe take a closer look at the application',
    agreeResultText: 'A fluffy kitty finds a forever home, and the adopter starts to come by the shelter regularly to volunteer.',
    disagreeResultText: 'Everything is in order, but you know that they know that you took a closer look. Awkward!',
    agreeEffect: [1, 4, 0, 0],
    disagreeEffect: [0, 0, -1, -4],
  ),
  Encounter(text: 'An adopter wants to haggle over price',
    agreeText: 'Explain what the costs are',
    disagreeText: 'Deny their adoption entirely!',
    agreeResultText: 'You tabulate the prices for spaying, vaccines, microchipping... but don\'t realize you have been suckered in by a master haggler! Somehow you end up OWNING $27 for the adoption.',
    disagreeResultText: 'A clever tactic. You are truly the haggliest of hagglers.',
    agreeEffect: [-16, 1, 4, 1],
    disagreeEffect: [5, 4, 0, 0],
  ),
  Encounter(text: 'A dog brings in a “stray” cat, but you suspect that the dog is just getting rid of its household competition.',
    agreeText: 'Send Rover a-roving',
    disagreeText: 'Accept that cat',
    agreeResultText: 'The dog vows to avenge this insult to honor, no mater how many dog years it might take. Ominous!',
    disagreeResultText: 'The cat is quite relieved to get out from under the thumb of its former housemate, and thrives in the company of other kitties.',
    agreeEffect: [1, 0, -9, 0],
    disagreeEffect: [0, 7, 0, 0],
  ),
  Encounter(text: 'Several people claim to have lost their wallet in the shelter recently. You check the cattery, and sure enough, one of the cats has been pilfering purses and waylaying wallets. This also explains the mysterious pallet of catnip that "no one" ordered.',
    agreeText: 'Return the property',
    disagreeText: 'Dispose of the property',
    agreeResultText: 'The victims are grateful, but find your explanation very suspicious.',
    disagreeResultText: 'You try to forget all about it, as you lock the felonious feline\'s cat condo. ',
    agreeEffect: [8, 0, -13, 0],
    disagreeEffect: [8, 0, -2, -3],
  ),
  Encounter(text: 'Can you take in a “stray” mountain lion?',
    agreeText: 'Heck no!',
    disagreeText: 'I\'ll try anything once!',
    agreeResultText: 'Seems reasonable, but where\'s the adventure?',
    disagreeResultText: 'You\'re a but flummoxed when you realize you need to find a way to adopt out your new charge. But no matter! After a few phone calls, you get the Matterhorn on the horn, and find that it is a mountain ready to adopt a lion. Rock on!',
    agreeEffect: [0, 0, 0, 0],
    disagreeEffect: [0, 4, 0, 4],
  ),
  Encounter(text: 'A newly arrived cat needs dental work.',
    agreeText: 'Fundraise via social media',
    disagreeText: 'Fundraise via snail mail',
    agreeResultText: 'The purpose of the internet? Pictures of cats. Your success is swift and the dentistry deft.',
    disagreeResultText: 'You attract enough attention after a few weeks, and pay for the operation. Meanwhile quite a few more retired folks come in to start volunteering.',
    agreeEffect: [0, 15, 0, 0],
    disagreeEffect: [1, 3, 3, 0],
  ),
  Encounter(text: 'You get a haircut, and the barber won’t stop talking the whole time. But then starts to follow you around town, showing up day after day.',
    agreeText: 'Tell that barber to beat it!',
    disagreeText: 'Wear a wig',
    agreeResultText: 'Your not-so-subtle point is finally accepted, but not before you are the recipient of a surprise buzz cut!',
    disagreeResultText: 'The barber eventually loses interest in looking for you, but laying low that long has taken its toll on your day-to-day.',
    agreeEffect: [0, 0, 3, -15],
    disagreeEffect: [-12, 0, 0, 1],
  ),
  Encounter(text: 'A geyser forms in the dog run.',
    agreeText: 'Charge admission',
    disagreeText: 'Harness its thermal energy',
    agreeResultText: '"Old Faithful" is taken, but would be apropos for a geyser in a dog run. You settle on the name "Up Dog" and make a mint as the cash starts to splash.',
    disagreeResultText: '"It\'s a different kind of harness than you are used to, but you now make so much electricity, the power company pays YOU!" --Yakov Smirnoff',
    agreeEffect: [13, -1, 4, 0],
    disagreeEffect: [19, -3, 0, 3],
  ),
  Encounter(text: 'The local college lists a snake charming class in their catalog. Are you the professor or a student?',
    agreeText: 'Professor',
    disagreeText: 'Student',
    agreeResultText: 'It\'s great to stand up straight and get a second job. It generates extra cash for the shelter! but working two jobs leaves you limp.',
    disagreeResultText: 'It\'s quite an enriching experience, and you find that the shelter cats\' tails are equally affected by your new skill!',
    agreeEffect: [8, 0, 0, -14],
    disagreeEffect: [0, 3, 4, 1],
  ),


];
  /*

volunteer orientation
need landscaping
need a new roof - money is tight
someone lost a love letter, only first names, do you advertise to get it back to them?
A meteor strikes nearby. investigate (alien tech food dispenser), or call for help (government cordons off area, mystery grant money…)
New dogs are so tiny, the slip out of kennels. buy aquariums?
The AI in your phone would like to adopt a cat
You go to buy kitty litter, but get lost in the back country for days. go north, go south, go bcak
Dog hypnosis? They are very well trained, but it wears off quickly after adoption :(
Driving to the vet’s office, you are lost. Stop to check map, or just try the next exit.
This is actually a tiger cub / lion / wolf
Do you go on an expidition to find the elephant graveyard?
The governor is looking for a new dog and stops in!
The axis of the earth’s gravity is off by 14 degrees inside the shelter. Tourism or perpetual motion?
Inside one of the kennels, you discover a portal to a dimension where everything is made of kibble
You find a cache of diamonds. One of the cats is a burglar!
Ants have infested the food. Do battle, or bargain with their queen?
You discover that one of the dog bowls turns dogs into puppies. Do you dare drink from it?
The security cameras have been failing at night 3:33am. Do you sleep over? It’s a ghost!!!!
Do you want enter a dog-o-thon race for charity?
A ghostly flying pirate ship descends onto the parking lot, and the captain demands cats. Call the cops, or buckle his swash?
Geologists have discovered a tiny active volcano next door. Move the shelter?
The rats in the attic wear tiny robes and worship the statue of a cat god
You find a cell phone in a kennel. One of the dogs runs a side business as a bookie.
While petting a cat, a genie pours forth! Do you dare make some wishes?
Do you allow a field trip from the elementary school? (kid tries to steal a puppy)
A witch is looking for a new familiar. Tell her to leave (face discrimination laws). Help (the whole coven ends up adopting here!)
The annual gala fundraiser. How much effort to put in? balance personal life and shelter profit
Busy day 4:55pm. Time for one more adoption? balance personal life and animal wellbeing
Animals are goin buggy. Spend time calming them, or an earthquake hits?
A musketeer cat demands to know why you run a prison
An old tome with a dog obedience spell
Best trainer in the world retires, donate (magical?) clicker. Sell, use at shelter, get famous?
One of the cats claims to actually be a raccoon. Let them go?
Spay appointment. Wait for cheaper vet. Book expensive vet now.
  */

