import 'package:shelter_adventure/components/inventory/item.dart';

// these are all the items in the game
final List<Item> theItems = [
  Item(
    itemId: '1',
    name: 'Mop and bucket',
    effectString: 'Bonus +15 starting Operations score',
    additiveBonus: [15, 0, 0, 0],
    costToUnlock: 10,
  ),
  Item(
    itemId: '2',
    name: 'Training Clickers',
    effectString: '50% bonus to Animals effects',
    multiplicativeBonus: [1.0, 1.5, 1.0, 1.0],
    costToUnlock: 30,
  ),
  Item(
    itemId: '3',
    name: 'Extra Nutritious Kibble Recipe',
    effectString: '+1 Animal score on every encounter',
    everyEncounterBonus: [0, 1, 0, 0],
    costToUnlock: 30,
  ),
  Item(
    itemId: '4',
    name: 'Yo-Yo',
    effectString: 'Bonus +25 starting Personal score',
    additiveBonus: [0, 0, 0, 25],
    costToUnlock: 75,
  ),
  Item(
    itemId: '4.5',
    name: 'Bowl of Candy',
    effectString: 'Bonus +25 starting Community score',
    additiveBonus: [0, 0, 25, 0],
    costToUnlock: 125,
  ),
  Item(
    itemId: '5',
    name: 'Lucky Power Crystal',
    effectString: 'Bonus +15 to all starting scores',
    additiveBonus: [15, 15, 15, 15],
    costToUnlock: 200,
  ),
  Item(
    itemId: '5.1',
    name: 'Flawless Staff Training Manaul',
    effectString: 'Double bonus to Operations scores',
    multiplicativeBonus: [2.0, 1.0, 1.0, 1.0],
    costToUnlock: 350,
  ),
  Item(
    itemId: '5.2',
    name: 'Mystically Enhanced Toy Design',
    effectString: '+3 Animal score on every encounter',
    everyEncounterBonus: [0, 3, 0, 0],
    costToUnlock: 50,
  ),
  Item(
    itemId: '5.3',
    name: 'Free Coffee In The Lobby',
    effectString: 'Bonus +25 starting Community score',
    additiveBonus: [0, 0, 25, 0],
    costToUnlock: 200,
  ),
  Item(
    itemId: '5.4',
    name: 'Self Help Book',
    effectString: '+4 Personal score on every encounter',
    everyEncounterBonus: [0, 0, 4, 0],
    costToUnlock: 200,
  ),
  Item(
    itemId: '6',
    name: 'Wi-Fi',
    effectString: '25% bonus to Operations effects',
    multiplicativeBonus: [1.25, 1.0, 1.0, 1.0],
    costToUnlock: 20,
  ),
  Item(
    itemId: '7',
    name: 'Public Artwork',
    effectString: '+4 Community score on every encounter',
    everyEncounterBonus: [0, 0, 4, 0],
    costToUnlock: 400,
  ),
  
  Item(
    itemId: '8',
    name: 'Coffee Machine',
    effectString: '2X bonus to Community effects',
    multiplicativeBonus: [1.0, 1.0, 2.0, 1.0],
    costToUnlock: 300
  ),
  Item(
    itemId: '9',
    name: 'Self Help Videos',
    effectString: '25% Bonus to Personal effects',
    multiplicativeBonus: [1.0, 1.0, 1.0, 1.25],
    costToUnlock: 20,
  ),
  Item(
    itemId: '9.5',
    name: 'Fanny Pack',
    effectString: 'Hold an extra item',
    bonusInventory: 2,
    costToUnlock: 25,
  ),
  Item(
    itemId: '10',
    name: 'Robot Receptionist',
    effectString: '+50 and 50% bonus to Operations',
    additiveBonus: [50, 0, 0, 0],
    multiplicativeBonus: [1.5, 1.0, 1.0, 1.0],
    costToUnlock: 125,
  ),
  Item(
    itemId: '11',
    name: 'Bark Translator',
    effectString: '+50 and 50% bonus to Animals',
    additiveBonus: [0, 50, 0, 0],
    multiplicativeBonus: [1.0, 1.5, 1.0, 1.0],
    costToUnlock: 125,
  ),
  Item(
    itemId: '12',
    name: 'Key to the City',
    effectString: '+50 and 50% bonus to Community',
    additiveBonus: [0, 0, 50, 0],
    multiplicativeBonus: [1.0, 1.0, 1.5, 1.0],
    costToUnlock: 125,
  ),
  Item(
    itemId: '13',
    name: 'Lucky Underpants',
    effectString: '+50 and 50% bonus to Personal',
    additiveBonus: [0, 0, 0, 50],
    multiplicativeBonus: [1.0, 1.0, 1.0, 1.5],
    costToUnlock: 125,
  ),
  Item(
    itemId: '14',
    name: 'Magic Flute',
    effectString: '+4 bonus turns',
    bonusTurns: 4,
    costToUnlock: 400,
  ),
  Item(
    itemId: '15',
    name: 'Big Fanny Pack',
    effectString: 'Hold two extra items',
    bonusInventory: 3,
    costToUnlock: 200,
  ),
  Item(
    itemId: '16',
    name: 'Lucky Rabbit\'s Shoe',
    effectString: '25% chance to reverse a negative effect, every encounter',
    costToUnlock: 3000,
  ),
  Item(
    itemId: '17',
    name: 'Magic Fiddle',
    effectString: '+6 bonus turns',
    bonusTurns: 6,
    costToUnlock: 4000,
  ),
  Item(
    itemId: '18',
    name: 'Crystal Ball',
    effectString: '+100 bonus to all stats',
    additiveBonus: [100, 100, 100, 100],
    costToUnlock: 6000,
  ),
  Item(
    itemId: '19',
    name: 'Dark Crystal Ball',
    effectString: '+300% bonus to all effects',
    multiplicativeBonus: [3.0, 3.0, 3.0, 3.0],
    costToUnlock: 13337,
  ),
];
